patchedDependencies:
  "@evolution-sdk/evolution@0.3.19": patches/@evolution-sdk__evolution@0.3.19.patch

onlyBuiltDependencies:
  - '@parcel/watcher'
  - cpu-features
  - esbuild
  - msgpackr-extract
  - protobufjs
  - ssh2
